apiVersion: v1
kind: Service
metadata:
  name: student-svc
  labels:
    app: student
spec:
  type: NodePort
  selector:
    app: student
  ports:
    - name: student-svc
      protocol: TCP
      port: 8080
      targetPort: 8080